/*
 * DrawOptionPanel.java
 *
 * Created on 18 de Julho de 2006, 18:24
 */

package antsystem.gui;

import javax.swing.ButtonGroup;

/**
 *
 * @author  danilo
 */
public class DrawOptionPanel extends javax.swing.JPanel {
    ButtonGroup toolButtonGroup;
    public static final int SELECT = 999;
    public static final int LINE = 1001;
    public static final int RECTANGLE = 1002;
    public static final int ELLIPSE = 1003;
    public static final int POLLY_LINE = 1004;
    
    public static final int PHEROMONE_LEVEL = 2000;
    /**
     * Creates new form DrawOptionPanel
     */
    public DrawOptionPanel() {
        initComponents();
        myInit();
    }
    
    public int getSelectedOptionType(){
        try{
            String buttomCommand = toolButtonGroup.getSelection().getActionCommand();
            if ("line".equals(buttomCommand))
                return LINE;
            if("rectangle".equals(buttomCommand))
                return RECTANGLE;
            if("ellipse".equals(buttomCommand))
                return ELLIPSE;
            if("polly_line".equals(buttomCommand))
                return POLLY_LINE;
            if("select".equals(buttomCommand))
                return SELECT;
            if("phLevel".equals(buttomCommand))
                return PHEROMONE_LEVEL;
            return 0;
        }catch (NullPointerException ne){
            return -1;
        }
    }
    
    public void setPheromoneLevel(int x, int y, int level){
        phPosition.setText("[" + x + ", " + y + "]" );
        phLevel.setText(Integer.toString(level));
    }
    
    public void myInit(){
        toolButtonGroup = new ButtonGroup();
        
        select.setActionCommand("select");
        line.setActionCommand("line");
        rectangle.setActionCommand("rectangle");
        ellipse.setActionCommand("ellipse");
        pollyLine.setActionCommand("polly_line");
        phLevelButton.setActionCommand("phLevel");
        toolButtonGroup.add(select);
        toolButtonGroup.add(line);
        toolButtonGroup.add(rectangle);
        toolButtonGroup.add(ellipse);
        toolButtonGroup.add(pollyLine);
        toolButtonGroup.add(phLevelButton);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        line = new javax.swing.JToggleButton();
        rectangle = new javax.swing.JToggleButton();
        ellipse = new javax.swing.JToggleButton();
        pollyLine = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        select = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        phLevelButton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        phPosition = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        phLevel = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Obstacles"));
        line.setText("line");

        rectangle.setText("rectangle");

        ellipse.setText("ellipse");

        pollyLine.setText("PollyLine");

        select.setText("Select");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, line)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, rectangle)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, ellipse))
                    .add(pollyLine))
                .addContainerGap(18, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(select)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(new java.awt.Component[] {ellipse, line, pollyLine, rectangle, select}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(line)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(rectangle)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ellipse)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pollyLine)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(select)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pheromone Level"));
        phLevelButton.setText("X");

        jLabel1.setText("Pos:");

        jLabel2.setText("Con:");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(phLevelButton)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(phPosition))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(phLevel)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(phPosition))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(phLevel))
                .add(15, 15, 15)
                .add(phLevelButton)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ellipse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton line;
    private javax.swing.JLabel phLevel;
    private javax.swing.JToggleButton phLevelButton;
    private javax.swing.JLabel phPosition;
    private javax.swing.JToggleButton pollyLine;
    private javax.swing.JToggleButton rectangle;
    private javax.swing.JToggleButton select;
    // End of variables declaration//GEN-END:variables
    
}
