/*
 * MainFrame.java
 *
 * Created on 12 de Junho de 2006, 22:49
 */

package antsystem.gui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;

import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;

import antsystem.model.Environment;

/**
 *
 * @author  Danilo N Costa
 */
public class MainFrame extends javax.swing.JFrame {
    private Environment environment;
    private String fpsStringLabel="FPS:", timeStringLabel="Time Elapsed:", 
            numOfAntsStringLabel="Num of Ants:", updatesStringLabel="Updates:";
    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        myInit();
    }
    
    public MainFrame(String title){
       
        this();
        super.setTitle(title);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        centerPanel = new javax.swing.JPanel();
        centerScrollPane = new javax.swing.JScrollPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        systemControlPanel = new antsystem.gui.SystemControlPanel();
        jPanel1 = new javax.swing.JPanel();
        drawOptionPanel = new antsystem.gui.DrawOptionPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        antConfigurationPanel = new antsystem.gui.AntConfigurationPanel();
        mainPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        southPanel = new javax.swing.JPanel();
        numOfAntsLabel = new javax.swing.JLabel();
        fpsLabel = new javax.swing.JLabel();
        updatesLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();

        centerPanel.setLayout(new java.awt.BorderLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(220, 500));
        systemControlPanel.setMinimumSize(new java.awt.Dimension(144, 550));
        jScrollPane1.setViewportView(systemControlPanel);

        jTabbedPane1.addTab("Main Control", jScrollPane1);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.add(drawOptionPanel, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Tools", jPanel1);

        jScrollPane2.setViewportView(antConfigurationPanel);

        jTabbedPane1.addTab("Ant Config", jScrollPane2);

        jSplitPane1.setLeftComponent(jTabbedPane1);

        mainPanel.setLayout(new java.awt.BorderLayout());

        titleLabel.setText("Some Title");
        mainPanel.add(titleLabel, java.awt.BorderLayout.NORTH);

        southPanel.setLayout(new java.awt.GridLayout(1, 0));

        numOfAntsLabel.setText("Num of Ants:");
        southPanel.add(numOfAntsLabel);
        numOfAntsLabel.getAccessibleContext().setAccessibleName("jLabeli");

        fpsLabel.setText("FPS:");
        southPanel.add(fpsLabel);

        updatesLabel.setText("Updates:");
        southPanel.add(updatesLabel);

        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        timeLabel.setText("Time Elapsed");
        southPanel.add(timeLabel);

        mainPanel.add(southPanel, java.awt.BorderLayout.SOUTH);

        jSplitPane1.setRightComponent(mainPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    public SystemControlPanel getSystemControlPanel(){
        return systemControlPanel;
        
    }
    public DrawOptionPanel getDrawOptionPanel(){
        return drawOptionPanel;
    }
    public void setEnvironment(Environment environment) {
        this.environment = environment;
        //environment.setBounds(0,0,environment.getWidth(), environment.getHeight());
        //environment.setPreferredSize(environment.getDimension());
        //centerPanel.add(new JScrollPane(environment), BorderLayout.CENTER);
        
        JPanel flowPanel = new JPanel(new FlowLayout());
        flowPanel.setBackground(Color.gray);
        flowPanel.add(environment);
        //centerScrollPane.setViewportView(flowPanel);
        JScrollPane scroller = new JScrollPane(flowPanel);
        mainPanel.add(scroller,BorderLayout.CENTER);
        systemControlPanel.setWidithText(""+environment.getPreferredSize().width);
        systemControlPanel.setHeightText(""+environment.getPreferredSize().height);
        //createBufferStrategy(2);
        //environment.setBufferStrategy(getBufferStrategy());
       System.out.println("adcionando environment");
       System.out.println("size: " + environment.getSize());
    }
    public Environment getEnvironment() {
        return environment;
    }
    
    public void setFPS(String fps){
        
        fpsLabel.setText(fpsStringLabel+fps);
    }
    
    public void setElapsedTime(String time){
        timeLabel.setText(timeStringLabel+time);
    }
    
    public void setTitle(String title){
        titleLabel.setText(title);
    }
    
    public void setNumOfAnts(String total){
        numOfAntsLabel.setText(numOfAntsStringLabel + " " + total);
    }
    
    public void setUpdates(String updates){
        updatesLabel.setText(updatesStringLabel + " " + updates);
    }
    public JTabbedPane getTabbedPane(){
        return jTabbedPane1;
    }
    
    public AntConfigurationPanel getAntConfiguration(){
        return antConfigurationPanel;
    }
    private void myInit() {
       pack();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private antsystem.gui.AntConfigurationPanel antConfigurationPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JScrollPane centerScrollPane;
    private antsystem.gui.DrawOptionPanel drawOptionPanel;
    private javax.swing.JLabel fpsLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel numOfAntsLabel;
    private javax.swing.JPanel southPanel;
    private antsystem.gui.SystemControlPanel systemControlPanel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel updatesLabel;
    // End of variables declaration//GEN-END:variables
    
}
