/*
 * SystemControlPanel.java
 *
 * Created on 12 de Junho de 2006, 21:46
 */

package antsystem.gui;

import antsystem.helper.ActionSupport;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author  danilo
 */
public class SystemControlPanel extends javax.swing.JPanel {
    private ActionSupport actionSupport = new ActionSupport(this);
    /** Creates new form SystemControlPanel */
    public SystemControlPanel() {
        initComponents();
        myInit();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        widthField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        heightField = new javax.swing.JTextField();
        resizeButton = new javax.swing.JButton();
        antsPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        numOfAntsField = new javax.swing.JTextField();
        addAntsButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        nestLocationButton = new javax.swing.JToggleButton();
        foodLocationButton = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        startButton = new javax.swing.JToggleButton();
        numOfUpdatesSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        stepButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        phIntervalSpinner = new javax.swing.JSpinner();
        phRateSpinner = new javax.swing.JSpinner();
        resetButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Environment Size"));
        jLabel1.setText("Width:");

        jLabel2.setText("Height:");

        resizeButton.setText("ok");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(resizeButton)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(heightField)
                            .add(widthField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(widthField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(22, 22, 22)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(heightField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(resizeButton))
        );

        antsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Nest Size"));
        antsPanel.setEnabled(false);
        jLabel3.setText("Ants:");

        addAntsButton.setText("+");

        org.jdesktop.layout.GroupLayout antsPanelLayout = new org.jdesktop.layout.GroupLayout(antsPanel);
        antsPanel.setLayout(antsPanelLayout);
        antsPanelLayout.setHorizontalGroup(
            antsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(antsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(antsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(addAntsButton)
                    .add(antsPanelLayout.createSequentialGroup()
                        .add(jLabel3)
                        .add(12, 12, 12)
                        .add(numOfAntsField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        antsPanelLayout.setVerticalGroup(
            antsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(antsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(antsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(numOfAntsField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 11, Short.MAX_VALUE)
                .add(addAntsButton))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Choose Location"));
        nestLocationButton.setText("Nest");

        foodLocationButton.setText("Food");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(nestLocationButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(foodLocationButton)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nestLocationButton)
                    .add(foodLocationButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Action"));
        startButton.setText("Start");

        jLabel4.setText(" updates / painting:");
        jLabel4.setToolTipText("Number of updates before painting");

        stepButton.setText("step");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 99, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(numOfUpdatesSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(startButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(stepButton)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(numOfUpdatesSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 26, Short.MAX_VALUE)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(startButton)
                    .add(stepButton)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pheromone Evaporation"));
        jLabel5.setText("Rate:");

        jLabel6.setText("Interval:");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel6)
                    .add(jLabel5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(phIntervalSpinner)
                    .add(phRateSpinner, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(phRateSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(phIntervalSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        resetButton.setText("Reset All");

        saveButton.setText("Save");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(antsPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(resetButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(saveButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(antsPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(resetButton)
                    .add(saveButton)))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void myInit(){
        addAntsButton.setEnabled(false);
        numOfAntsField.setEditable(false);
        
        numOfUpdatesSpinner.setModel(new SpinnerNumberModel(1,1,10000,1));
        phIntervalSpinner.setModel(new SpinnerNumberModel(1,1,10000,1));
        phRateSpinner.setModel(new SpinnerNumberModel(0,0,10000,1));
        nestLocationButton.setActionCommand("nest");
        nestLocationButton.addActionListener(actionSupport);
        foodLocationButton.setActionCommand("food");
        foodLocationButton.addActionListener(actionSupport);
        stepButton.addActionListener(actionSupport);
        stepButton.setActionCommand("step");
        startButton.setActionCommand("start");
        startButton.addActionListener(actionSupport);
        startButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (startButton.getActionCommand().equals("start")){
                    startButton.setText("Pause");
                    startButton.setActionCommand("stop");
                    numOfUpdatesSpinner.setEnabled(false);
                    phIntervalSpinner.setEnabled(false);
                    phRateSpinner.setEnabled(false);
                    stepButton.setEnabled(false);
                }else{
                    startButton.setText("Start");
                    startButton.setActionCommand("start");
                    numOfUpdatesSpinner.setEnabled(true);
                    phIntervalSpinner.setEnabled(true);
                    phRateSpinner.setEnabled(true);
                    stepButton.setEnabled(true);
                }
                    
            }
        });
        
        addAntsButton.setActionCommand("addAnts");
        addAntsButton.addActionListener(actionSupport);
        resizeButton.setActionCommand("resize");
        resizeButton.addActionListener(actionSupport);
        resetButton.setActionCommand("reset");
        resetButton.addActionListener(actionSupport);
    }
    
    public void allowAddingAnts(){
        numOfAntsField.setEditable(true);
        addAntsButton.setEnabled(true);
    }
    public void setNestButtonState(boolean selected){
        nestLocationButton.setSelected(selected);
    }
    
    public void setFoodButtonState(boolean selected){
        foodLocationButton.setSelected(selected);
        
    }
    
    public void setWidithText(String text){
        widthField.setText(text);
    }
    
    public String getWidthText(){
        return widthField.getText();
    }
    
    public void setHeightText(String text){
        heightField.setText(text);
    }
    
    public String getHeightText(){
        return heightField.getText();
    } 
    
    public String getNumOfAntsText(){
        return numOfAntsField.getText().trim();
    }
    public void addActionListener(ActionListener al){
        this.actionSupport.addActionListener(al);
    }
    
    public int getNumOfUpdatesBeforePainting(){
        return ((Integer)numOfUpdatesSpinner.getValue()).intValue();
    }
    public int getPheromoneEvaporationRate(){
        return ((Integer)phRateSpinner.getValue()).intValue();
    }
    
    public int getPheromoneEvaporationInterval(){
        return ((Integer)phIntervalSpinner.getValue()).intValue();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAntsButton;
    private javax.swing.JPanel antsPanel;
    private javax.swing.JToggleButton foodLocationButton;
    private javax.swing.JTextField heightField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JToggleButton nestLocationButton;
    private javax.swing.JTextField numOfAntsField;
    private javax.swing.JSpinner numOfUpdatesSpinner;
    private javax.swing.JSpinner phIntervalSpinner;
    private javax.swing.JSpinner phRateSpinner;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton resizeButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JToggleButton startButton;
    private javax.swing.JButton stepButton;
    private javax.swing.JTextField widthField;
    // End of variables declaration//GEN-END:variables
    
}
